declare namespace sits {
    type If = "If";
    type Else = "Else";
    type ElseIf = "ElseIf";
    type Do = "Do";
    type While = "While";
    type Break = "Break";
    type Continue = "Continue";
    type Return = "Return";
    type set = "set";
    type to = "to";
    type lt = "lt";
    type le = "le";
    type gt = "gt";
    type ge = "ge";
    type eq = "eq";
    type ne = "ne";
    type add = "add";
    type sub = "sub";
    type mul = "mul";
    type div = "div";
    type mod = "mod";
    type then = "then";
    type oops = "oops";
    type well = "well";
    type phew = well;
}
